name = "MultilineStrings"
uuid = "1e8d2bf6-9821-4900-9a2f-4d87552df2bd"
authors = ["Invenia Technical Computing Corporation"]
version = "1.0.0"

[compat]
Aqua = "0.8.11"
Test = "1"
YAML = "0.4"
julia = "1"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[targets]
test = ["Aqua", "Test", "YAML"]
