---
name: Format
on:
  pull_request:
    types: [opened, reopened, synchronize, labeled, unlabeled]
    paths:
      - "**/*.jl"
      - ".github/workflows/Format.yml"
jobs:
  code-style:
    runs-on: ubuntu-latest
    steps:
      - uses: julia-actions/julia-format@v3
        with:
          version: "1"
          suggestion-label: ""  # format-suggest
